[feature] driver/netio: use netio via json-api
JUMO-GmbH-Co-KG/labgrid pull request #1
Opened 2023-07-06 11:33 UTC by ActionHOSchT

Following the contribution-guidelines an additional functionality using the netio-json-api was added to simplify netio handling. To get all actions working powerprotocol.py:NetworkPowerDriver probably needs a refactor.

Signed-off-by: Raffael Krakau <r.krakau90@gmail.com>

Die folgenden Zeilen dienen dem Nachvollziehen von ÄÜnderung und sollten bei einem weiteren squash entfernt werden _____________________________________________________ rename methods
add netio_json into tests
make class and its contents private
update doc
breaking changes::: remove main and successors
match naming conventions and refactor comments
match netio-json-driver to contribution-guidelines _____________________________________________________

**Description**

**Checklist**
- [ ] Documentation for the feature
- [ ] Tests for the feature 

- [ ] The arguments and description in doc/configuration.rst have been updated

- [ ] Add a section on how to use the feature to doc/usage.rst

- [ ] Add a section on how to use the feature to doc/development.rst

- [ ] PR has been tested

- [ ] Man pages have been regenerated

2023-07-06 13:55 UTC, ChHapp requested changes

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +
Die Leerzeile könnte von mir aus weg

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +        """
Den Kommentar könntest du auch entfernen - sag ja nichts groß aus

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +    def get_state(self, socketID):
Funktioniert das mit dem get nun? Liegt es an diesem Treiber oder geht es mit dem `netio` power treiber auch nicht?

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +        cast socketID to int
```suggestion
        Cast socketID to int
```

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +        Build URL from params set in __init__()
```suggestion
        Generate request URL from given params
```

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +
leerzeile könnte weg

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +        requestUrl += self.__host
Könnten wir das hier vereinfachen sprich der Port könnte man doch gleich mit anhängen

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +    set netio-state at index(socketID)
```suggestion
    Set netio-state at index(socketID)
```

2023-07-06 13:55 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +    get power-state as json
```suggestion
    Get power-state as json
```

2023-07-06 14:00 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +    def get_state(self, socketID):
![image](https://github.com/JUMO-GmbH-Co-KG/labgrid/assets/73703991/d5c6e258-c73d-466b-b23f-f4e5a4b20e82)

Ja, ist mit getestet.

2023-07-06 14:36 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +
isort forciert diese jedoch und ist demnach von pengutronics gefordert.

2023-07-06 14:59 UTC, EugenWiens approved these changes

2023-07-06 15:11 UTC, ChHapp commented on labgrid/driver/power/netio_json.py
> +
:ok_hand:

2023-07-07 06:27 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +        """
done

2023-07-07 06:27 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +        cast socketID to int
done

2023-07-07 06:28 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +        Build URL from params set in __init__()
done

2023-07-07 06:28 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +
done

2023-07-07 06:29 UTC, ActionHOSchT commented on labgrid/driver/power/netio_json.py
> +        requestUrl += self.__host
done
![image](https://github.com/JUMO-GmbH-Co-KG/labgrid/assets/73703991/6e380aab-459d-4b3d-b164-1ef99df29e62)

2023-07-10 04:40 UTC, ChHapp commented on doc/configuration.rst
> +  .. code-block:: yaml
Die Formatierung nochmal prüfen, bei mir wird es nicht richtig angezeigt

2023-07-10 04:40 UTC, ChHapp commented on doc/configuration.rst
> +  .. code-block:: yaml
leerzeile einfügen

2023-07-10 08:32 UTC, ActionHOSchT commented on doc/configuration.rst
> +  .. code-block:: yaml
done

2023-07-10 08:32 UTC, ActionHOSchT commented on doc/configuration.rst
> +  .. code-block:: yaml
done

2023-07-10 08:48 UTC, ChHapp commented on doc/configuration.rst
> +    NetworkPowerPort:
auf den zweiten Blick - wird das hier überhaupt gebraucht?

2023-07-11 13:24 UTC, ChHapp approved these changes
Looks good to me :+1:

2023-07-11 13:24 UTC, merged